defaults: &defaults
  working_directory: ~/analytics-clj
  docker:
    - image: clojure:lein

version: 2

jobs:
  clj-kondo:
    docker:
      - image: cljkondo/clj-kondo:2024.03.13
    steps:
      - checkout
      - run: clj-kondo --lint .

  docs:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein codox

  test:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein check
      - run: lein test

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein deploy

workflows:
  version: 2
  test_and_publish:
    jobs:
      - clj-kondo:
          filters:
            tags:
              only: /.*/
      - docs:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: clojars-publish
          requires:
            - clj-kondo
            - docs
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
