defaults: &defaults
  working_directory: ~/analytics-clj
  docker:
    - image: clojure:lein

version: 2

jobs:
  clj-kondo:
    docker:
      - image: cljkondo/clj-kondo:2024.03.13
    steps:
      - checkout
      - run: clj-kondo --lint .

  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}

      - run: lein deps

      - run: lein check

      - save_cache:
          key: v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}
          paths:
            - "~/.m2"

  docs:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}

      - run: lein codox

      - save_cache:
          key: v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}
          paths:
            - "~/.m2"

  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}

      - run: lein test

      - save_cache:
          key: v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}
          paths:
            - "~/.m2"

workflows:
  version: 2
  build_and_test:
    jobs:
      - clj-kondo
      - build
      - docs
      - test:
          requires:
            - build
