defaults: &defaults
  working_directory: ~/analytics-clj
  docker:
    - image: clojure:lein

version: 2

jobs:
  clj-kondo:
    docker:
      - image: cljkondo/clj-kondo:2024.03.13
    steps:
      - checkout
      - run: clj-kondo --lint .

  check:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein check

  docs:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein codox

  test:
    <<: *defaults
    steps:
      - checkout
      - run: lein deps
      - run: lein test

workflows:
  version: 2
  build_and_test:
    jobs:
      - clj-kondo
      - check
      - docs
      - test
